remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 
title: [SYD HOME]
description: [Welcome to my website]
github:
  zip_url: http://example.com/download.zip
  another_url: another value
